services:
  db_annonces:
    image: postgres:15
    container_name: annonces_db
    environment:
      POSTGRES_DB: annonces_db
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_pass
    ports:
      - "5433:5432"
    volumes:
      - annonces_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agrobloc-network

volumes:
  annonces_data:

networks:
  agrobloc-network:
    name: agrobloc-network
